In [47]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    category
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    category
 8   class        891 non-null    category
 9   who          891 non-null    category
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    category
 13  alive        891 non-null    category
 14  alone        891 non-null    bool
dtypes: bool(2), category(7), float64(2), int64(4)
memory usage: 50.8 KB

In [49]:
# Practise Day 2

# df_csv.columns
if {'survived','sex'}.issubset(df_csv.columns):
    mask_adult =  df['age'].ge(18)
    mask_female = df['sex'].astype(str).str.lower().eq('female')
elif {'species','sepal_length'}.issubset(df.columns)

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888     True
889    False
890    False
Name: sex, Length: 891, dtype: bool

# Pandas Practice – Built‑in Dataset (Seaborn Titanic or Iris Fallback)

*Generated on 2025-09-28*

This notebook lets you start immediately without hunting for a CSV. It will:

1. **Try** to load Seaborn's `titanic` dataset.
2. If that fails (no internet), it will **fallback** to scikit‑learn's `iris` dataset.
3. It will also **save the dataset to CSV** locally so you can practice real IO with `pd.read_csv`.

> All plots use matplotlib (no seaborn plotting) so the notebook runs in offline environments.

## 0) Environment Setup & Data Load (with CSV export)
This cell loads a dataset and saves it as `practice_data.csv` locally.

In [1]:
# If needed:
# %pip install pandas matplotlib scikit-learn seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

loaded = None
note = ""

# Try Seaborn Titanic first (may require internet on first use)
try:
    import seaborn as sns
    try:
        df = sns.load_dataset('titanic')  # may fetch online; cached afterwards
        loaded = "titanic"
        note = "Loaded seaborn.titanic"
    except Exception as e:
        raise RuntimeError(f"Seaborn present but load_dataset failed: {e}")
except Exception as _:
    pass

# Fallback: scikit-learn iris (always offline)
if loaded is None:
    from sklearn.datasets import load_iris
    iris = load_iris(as_frame=True)
    df = iris.frame.copy()
    # Align to a friendly schema
    df.rename(columns={
        'sepal length (cm)':'sepal_length',
        'sepal width (cm)':'sepal_width',
        'petal length (cm)':'petal_length',
        'petal width (cm)':'petal_width',
        'target':'species_id'
    }, inplace=True)
    # Map numeric target to species names
    df['species'] = iris.target_names[df['species_id']]
    df.drop(columns=['species_id'], inplace=True)
    loaded = "iris"
    note = "Loaded sklearn.iris (fallback)"

# Save to CSV so you can practice file IO
csv_path = "practice_data.csv"
df.to_csv(csv_path, index=False)

print(f"{note}. Shape: {df.shape}. Saved CSV -> {csv_path}")
df.head()

Loaded seaborn.titanic. Shape: (891, 15). Saved CSV -> practice_data.csv

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

loaded = None
note = ""


try:
    import seaborn as sns

    
except Exception as e:
    raise RuntimeError(f"Seaborn not present and could not be imported : {e}")


try:
    df = sns.load_dataset('titanic')
    loaded = "titanic"
    note = "Loaded seaborn.titanic"

except Exception as e:
    raise RuntimeError(f"Seaborn present but load_dataset failed: {e}")


if loaded :
    print(f"success in loading data ")

else:
    print(f"file not in loading data ")

file_path = "practise_data_saved.csv"

df.to_csv(file_path, index=False)

success in loading data

## 0.1) Data Snapshot & Dictionary
Quick overview of columns and types.

In [2]:
print(f"share info about the dataframe\n")
df.info()
print(f"\nshare number of na row count per columns\n")
df.isna().sum()

print(f"\nBasic Describe (Numeric)\n")
df.describe()

share info about the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

share number of na row count per columns


Basic Describe (Numeric)

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [3]:
df.info()
print("\nMissing values per column:")
print(df.isna().sum())

print("\nFirst 5 rows:")
display(df.head())

print("\nBasic describe (numeric):")
display(df.describe())

print("\nIf 'titanic' columns exist, you'll see familiar fields like 'survived', 'class', 'sex', 'age', 'fare'.")
print("If not, you're likely on the Iris fallback with 'sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'.")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

Missing values per column:
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

First 5 rows:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Basic describe (numeric):

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

If 'titanic' columns exist, you'll see familiar fields like 'survived', 'class', 'sex', 'age', 'fare'.
If not, you're likely on the Iris fallback with 'sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'.

In [5]:
df_csv = pd.read_csv('practise_data_saved.csv')

df_csv.head(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False

In [6]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

In [17]:
path = 'practise_data_saved.csv'
df_csv = pd.read_csv(path)

obj_cols = df_csv.select_dtypes(include='object').columns.tolist()
for col in obj_cols:
    if  df_csv[col].nunique()/ max(len(df_csv),1) < 0.5:
        df_csv[col] = df_csv[col].astype('category')

for num_col in ['age','fare']:
    if num_col in df_csv.columns:
        df_csv[num_col] = pd.to_numeric(df_csv[num_col], errors='coerce')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    category
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    category
 8   class        891 non-null    category
 9   who          891 non-null    category
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    category
 13  alive        891 non-null    category
 14  alone        891 non-null    bool
dtypes: bool(2), category(7), float64(2), int64(4)
memory usage: 50.8 KB

## Day 1 — IO + Inspection
**Goal:** load from CSV, fix dtypes, inspect memory & missingness.

In [45]:
print(f"\nMemory usage (deep)\n")
# print(df.memory_usage(deep=True).sum(),'bytes')
print(df.memory_usage(deep=False).sum(),'zzzzzz')

Memory usage (deep)

82592 zzzzzz

In [10]:
df_csv.isna().sum().sort_values(ascending = False)

deck           688
age            177
embarked         2
embark_town      2
survived         0
pclass           0
sex              0
sibsp            0
parch            0
fare             0
class            0
who              0
adult_male       0
alive            0
alone            0
dtype: int64

In [35]:
# print(df_csv['age'].dtypes)
# print(df_csv['age'].dtypes.kind)




if 'age' in df_csv.columns:
    # print(df_csv.columns)
    # assert df['embarked'].dtype.kind in "fiub", "age should be numeric"
    assert df['embarked'].dtype.kind in "fiub", "age should be numeric"
    print(df['embarked'].dtype.kind )
    print(df['embarked'].dtype )

AssertionError: age should be numeric

In [2]:
# GOAL: Read the CSV we just saved and inspect it.
path = "practice_data.csv"
df = pd.read_csv(path)

# If Titanic, parse some dates if any (not present by default), ensure category dtypes.
# We'll conditionally set categoricals depending on which dataset we loaded.

# Identify likely categorical columns by heuristics
obj_cols = df.select_dtypes(include='object').columns.tolist()
for col in obj_cols:
    # If ratio of unique values is below 50%, make it category to save memory
    if df[col].nunique() / max(len(df),1) < 0.5:
        df[col] = df[col].astype('category')

# Example titanic-specific coercions if present
for num_col in ['age','fare']:
    if num_col in df.columns:
        df[num_col] = pd.to_numeric(df[num_col], errors='coerce')

df.info()
print("\nMemory usage (deep):")
print(df.memory_usage(deep=True).sum(), "bytes")

print("\nMissing values per column:")
print(df.isna().sum().sort_values(ascending=False))

# SELF-CHECKS
if 'age' in df.columns:
    assert df['age'].dtype.kind in "fiub", "age should be numeric"
if 'species' in df.columns:
    assert str(df['species'].dtype) in ("category","object"), "species should be categorical-like"

print("\n✅ Day 1 checks passed")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    category
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    category
 8   class        891 non-null    category
 9   who          891 non-null    category
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    category
 13  alive        891 non-null    category
 14  alone        891 non-null    bool
dtypes: bool(2), category(7), float64(2), int64(4)
memory usage: 50.8 KB

Memory usage (deep):
53262 bytes

Missing values per column:
deck           688
age            177
embarked         2
embark_town      2
survived         0
pclass           0
sex              0
sibsp            0
parch            0
fare             0
class            0
who              0
adult_male       0
alive            0
alone            0
dtype: int64

✅ Day 1 checks passed

## Day 2 — Indexing & Filtering (`.loc` vs `.iloc`)
**Goal:** practice boolean masks, safe assignment, and comparing loc/iloc.

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   survived      891 non-null    int64
 1   pclass        891 non-null    int64
 2   sex           891 non-null    category
 3   age           714 non-null    float64
 4   sibsp         891 non-null    int64
 5   parch         891 non-null    int64
 6   fare          891 non-null    float64
 7   embarked      889 non-null    category
 8   class         891 non-null    category
 9   who           891 non-null    category
 10  adult_male    891 non-null    bool
 11  deck          203 non-null    category
 12  embark_town   889 non-null    category
 13  alive         891 non-null    category
 14  alone         891 non-null    bool
 15  adult_female  206 non-null    object
dtypes: bool(2), category(7), float64(2), int64(4), object(1)
memory usage: 57.8+ KB

In [61]:
# -------------Day 2 practise --------------------

if {'survived','sex'}.issubset(df.columns):
    # print('Hell Yes')
    mask_adult =  df['age'].ge(18)
    mask_female = df['sex'].astype(str).str.lower().eq('female')
    df.loc[mask_adult & mask_female,'adult_female'] =  True
elif {'species','sepal_length'}.issubset(df.columns):
    # mask_long = df['sepal_length'].ge(df)
    mask_long = df['sepal_length'].ge(df['sepal_length'].median())
    mask_setosa = df['species'].astype(str).str.lower().eq('setosa')

    df.loc[mask_long & mask_setosa, 'long_setosa']  = True

# Iloc demonstration

first_three_columns = df.columns[:3]
print(first_three_columns)    
print("First 3 rows and First three columns\n")
# display(df.iloc[:3,:3])

#SELF CHECK


if 'adult_female' in df.columns:
    assert df.loc[mask_adult & mask_female, 'adult_female'].all()
if 'long_setosa' in df.columns:
    assert df.loc[mask_long & mask_setosa, 'long_setosa'].all(),"species should be categorical-like"

# df.columns.sort_values(ascending = True).tolist()
# sorted(df.columns.tolist(), reverse= False)

print("Day 2 check passed")

Index(['survived', 'pclass', 'sex'], dtype='object')
First 3 rows and First three columns

Day 2 check passed

In [35]:
# Create mask examples based on available columns
if {'survived','sex'}.issubset(df.columns):
    mask_adult = df['age'].ge(18)
    mask_female = df['sex'].astype(str).str.lower().eq('female')
    df.loc[mask_adult & mask_female, 'adult_female'] = True
elif {'species','sepal_length'}.issubset(df.columns):
    mask_long = df['sepal_length'].ge(df['sepal_length'].median())
    mask_setosa = df['species'].astype(str).str.lower().eq('setosa')
    df.loc[mask_long & mask_setosa, 'long_setosa'] = True

# iloc demonstration (position-based)
first_three_cols = df.columns[:3]
print("First 3 rows, first 3 cols via iloc:")
display(df.iloc[:3, :3])

# SELF-CHECK
if 'adult_female' in df.columns:
    assert df.loc[mask_adult & mask_female, 'adult_female'].all()
if 'long_setosa' in df.columns:
    assert df.loc[mask_long & mask_setosa, 'long_setosa'].all()

print("\n✅ Day 2 checks passed")

First 3 rows, first 3 cols via iloc:

   survived  pclass     sex
0         0       3    male
1         1       1  female
2         1       3  female

✅ Day 2 checks passed

## Day 3 — Missing Data (`isna`, `fillna`, drop vs fill)
**Goal:** profile NA and apply group-wise fills where sensible.

In [ ]:
na_counts = df.isna().sum().sort_values(ascending=False)
print("Top missing columns:")
print(na_counts.head())

# Example: group-wise fill for Titanic 'age' by 'class' or 'sex'
if {'age','class'}.issubset(df.columns):
    df['age'] = df['age'].fillna(df.groupby('class')['age'].transform('median'))
elif {'sepal_length','species'}.issubset(df.columns):
    # Iris rarely has NA; demo imputation by species group (no-op if no NA)
    df['sepal_length'] = pd.to_numeric(df['sepal_length'], errors='coerce')
    df['sepal_length'] = df['sepal_length'].fillna(df.groupby('species')['sepal_length'].transform('median'))

# SELF-CHECK: chosen feature should have no NA now (if it existed)
if 'age' in df.columns:
    assert df['age'].isna().sum() == 0
else:
    assert df['sepal_length'].isna().sum() == 0

print("\n✅ Day 3 checks passed")

## Day 4 — Type Coercion (dates, numerics, categoricals)
**Goal:** coerce problem columns and verify types.

In [ ]:
# Numeric coercions
for col in df.columns:
    if col.lower() in {'age','fare','pclass','sepal_length','sepal_width','petal_length','petal_width'}:
        df[col] = pd.to_numeric(df[col], errors='coerce')

# Categorical coercions
for col in df.select_dtypes(include='object').columns:
    if df[col].nunique() / max(len(df),1) < 0.5:
        df[col] = df[col].astype('category')

# SELF-CHECKS
if 'fare' in df.columns:
    assert pd.api.types.is_float_dtype(df['fare'])
if 'species' in df.columns:
    assert pd.api.types.is_categorical_dtype(df['species']) or pd.api.types.is_object_dtype(df['species'])

print("\n✅ Day 4 checks passed")

## Day 5 — Sorting & Ranking
**Goal:** multi-column sort and group-wise ranks.

In [ ]:
if {'class','fare'}.issubset(df.columns):
    df = df.sort_values(['class','fare'], ascending=[True, False]).copy()
    df['fare_rank_in_class'] = df.groupby('class')['fare'].rank('dense', ascending=False)
    # SELF-CHECK
    assert df['fare_rank_in_class'].ge(1).all()
elif {'species','sepal_length'}.issubset(df.columns):
    df = df.sort_values(['species','sepal_length'], ascending=[True, False]).copy()
    df['len_rank_in_species'] = df.groupby('species')['sepal_length'].rank('dense', ascending=False)
    # SELF-CHECK
    assert df['len_rank_in_species'].ge(1).all()

print("\n✅ Day 5 checks passed")

## Week 2 — Grouping & Reshaping
**Goal:** `groupby`, `agg`, `pivot_table`, `melt`.

In [ ]:
# GroupBy examples
if {'survived','sex'}.issubset(df.columns):
    summary = (df.groupby(['sex','class'], observed=True)
                 .agg(survival_rate=('survived','mean'),
                      avg_age=('age','mean'),
                      n=('survived','size'))
                 .reset_index())
    display(summary.head())
else:
    summary = (df.groupby('species', observed=True)
                 .agg(mean_len=('sepal_length','mean'),
                      mean_wid=('sepal_width','mean'),
                      n=('species','size'))
                 .reset_index())
    display(summary.head())

# Reshaping with pivot_table
if {'survived','class','sex'}.issubset(df.columns):
    pt = pd.pivot_table(df, index='class', columns='sex', values='survived', aggfunc='mean')
    display(pt)
else:
    pt = pd.pivot_table(df, index='species', values='sepal_length', aggfunc='mean')
    display(pt)

# Melt back to long
long = pt.reset_index().melt(id_vars=pt.index.name, var_name='key', value_name='value')
display(long.head())

print("\n✅ Week 2 basic grouping/reshaping done")

## Week 3 — Performance & Quality Gates
**Goal:** vectorize operations and assert data quality.

In [ ]:
# Vectorized bucketing example
num_col = None
for c in ['fare','age','sepal_length']:
    if c in df.columns:
        num_col = c
        break

if num_col:
    df['bucket'] = pd.cut(df[num_col], bins=[-np.inf, 0, df[num_col].median(), df[num_col].quantile(0.9), np.inf],
                          labels=['neg_or_zero','low','mid','high'])
    assert df['bucket'].notna().mean() > 0.9

# Quality checks (adapt to dataset)
if 'survived' in df.columns:
    assert set(df['survived'].dropna().unique()) <= {0,1}
if 'sepal_length' in df.columns:
    assert (df['sepal_length'] > 0).all()

print("\n✅ Week 3 checks passed")

## Week 4 — Mini Project
Pick the branch that matches your dataset.

In [ ]:
# Titanic: compute survival rate by class & sex, and plot.
if {'survived','class','sex'}.issubset(df.columns):
    rates = (df.groupby(['class','sex'], observed=True)['survived']
               .mean()
               .reset_index())
    print("Survival rates by class & sex:")
    display(rates)
    # Plot (matplotlib only)
    plt.figure()
    for c in sorted(df['class'].astype(str).unique()):
        subset = rates[rates['class'].astype(str)==c]
        plt.plot(subset['sex'].astype(str), subset['survived'], marker='o', label=f"class {c}")
    plt.title("Titanic Survival Rate by Class & Sex")
    plt.xlabel("Sex")
    plt.ylabel("Survival Rate")
    plt.legend()
    plt.show()

# Iris: compute per-species feature means and plot a simple line for sepal stats
elif {'species','sepal_length','sepal_width'}.issubset(df.columns):
    means = (df.groupby('species', observed=True)[['sepal_length','sepal_width']]
               .mean()
               .reset_index())
    print("Iris means by species:")
    display(means)
    plt.figure()
    plt.plot(means['species'].astype(str), means['sepal_length'], marker='o', label='sepal_length')
    plt.plot(means['species'].astype(str), means['sepal_width'], marker='o', label='sepal_width')
    plt.title("Iris Mean Sepal Length & Width by Species")
    plt.xlabel("Species")
    plt.ylabel("Centimeters")
    plt.legend()
    plt.show()

## Appendix — Tips & Pitfalls

In [ ]:
# Avoid chained assignment:
# BAD:  df[df.a>0]['b'] = 1
# GOOD: df.loc[df.a>0, 'b'] = 1

# Safer merges:
# merged = left.merge(right, on='key', how='left', validate='many_to_one')

# Quick schema assert:
# expected = {'species':'category','sepal_length':'float64'}
# actual = df.dtypes.astype(str).to_dict()
# for k,v in expected.items():
#     print(k, actual.get(k))