In [2]:
import pandas as pd

In [4]:
data_df = pd.read_csv("symbols_valid_meta.csv")

In [7]:
data_df.head(5)

,Nasdaq Traded,Symbol,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
0,Y,A,"Agilent Technologies, Inc. Common Stock",N,,N,100.0,N,NaN,A,A,N
1,Y,AA,Alcoa Corporation Common Stock,N,,N,100.0,N,NaN,AA,AA,N
2,Y,AAAU,Perth Mint Physical Gold ETF,P,,Y,100.0,N,NaN,AAAU,AAAU,N
3,Y,AACG,ATA Creativity Global - American Depositary Sh...,Q,G,N,100.0,N,N,NaN,AACG,N
4,Y,AADR,AdvisorShares Dorsey Wright ADR ETF,P,,Y,100.0,N,NaN,AADR,AADR,N

In [13]:
data_df["Symbol"].dtype

dtype('O')

In [8]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8049 entries, 0 to 8048
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Nasdaq Traded     8049 non-null   object
 1   Symbol            8049 non-null   object
 2   Security Name     8049 non-null   object
 3   Listing Exchange  8049 non-null   object
 4   Market Category   8049 non-null   object
 5   ETF               8049 non-null   object
 6   Round Lot Size    8049 non-null   float64
 7   Test Issue        8049 non-null   object
 8   Financial Status  3383 non-null   object
 9   CQS Symbol        4666 non-null   object
 10  NASDAQ Symbol     8049 non-null   object
 11  NextShares        8049 non-null   object
dtypes: float64(1), object(11)
memory usage: 754.7+ KB

In [14]:
print(data_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8049 entries, 0 to 8048
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Nasdaq Traded     8049 non-null   object
 1   Symbol            8049 non-null   object
 2   Security Name     8049 non-null   object
 3   Listing Exchange  8049 non-null   object
 4   Market Category   8049 non-null   object
 5   ETF               8049 non-null   object
 6   Round Lot Size    8049 non-null   float64
 7   Test Issue        8049 non-null   object
 8   Financial Status  3383 non-null   object
 9   CQS Symbol        4666 non-null   object
 10  NASDAQ Symbol     8049 non-null   object
 11  NextShares        8049 non-null   object
dtypes: float64(1), object(11)
memory usage: 754.7+ KB
None

In [16]:
data_df.head(5)

,Nasdaq Traded,Symbol,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
0,Y,A,"Agilent Technologies, Inc. Common Stock",N,,N,100.0,N,NaN,A,A,N
1,Y,AA,Alcoa Corporation Common Stock,N,,N,100.0,N,NaN,AA,AA,N
2,Y,AAAU,Perth Mint Physical Gold ETF,P,,Y,100.0,N,NaN,AAAU,AAAU,N
3,Y,AACG,ATA Creativity Global - American Depositary Sh...,Q,G,N,100.0,N,N,NaN,AACG,N
4,Y,AADR,AdvisorShares Dorsey Wright ADR ETF,P,,Y,100.0,N,NaN,AADR,AADR,N

In [17]:
data_df["Symbol"] = data_df["Symbol"].astype("string")

In [19]:
data_df["Symbol"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 8049 entries, 0 to 8048
Series name: Symbol
Non-Null Count  Dtype
--------------  -----
8049 non-null   string
dtypes: string(1)
memory usage: 63.0 KB

In [20]:
data_df["Symbol"].nunique()

8049

In [25]:
data_df.shape

(8049, 12)

In [23]:
len(data_df)

8049

In [26]:
data_df["Symbol"] = data_df["Symbol"].astype("string")

In [27]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8049 entries, 0 to 8048
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Nasdaq Traded     8049 non-null   object
 1   Symbol            8049 non-null   string
 2   Security Name     8049 non-null   object
 3   Listing Exchange  8049 non-null   object
 4   Market Category   8049 non-null   object
 5   ETF               8049 non-null   object
 6   Round Lot Size    8049 non-null   float64
 7   Test Issue        8049 non-null   object
 8   Financial Status  3383 non-null   object
 9   CQS Symbol        4666 non-null   object
 10  NASDAQ Symbol     8049 non-null   object
 11  NextShares        8049 non-null   object
dtypes: float64(1), object(10), string(1)
memory usage: 754.7+ KB

In [28]:
data_df.head(5)

,Nasdaq Traded,Symbol,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
0,Y,A,"Agilent Technologies, Inc. Common Stock",N,,N,100.0,N,NaN,A,A,N
1,Y,AA,Alcoa Corporation Common Stock,N,,N,100.0,N,NaN,AA,AA,N
2,Y,AAAU,Perth Mint Physical Gold ETF,P,,Y,100.0,N,NaN,AAAU,AAAU,N
3,Y,AACG,ATA Creativity Global - American Depositary Sh...,Q,G,N,100.0,N,N,NaN,AACG,N
4,Y,AADR,AdvisorShares Dorsey Wright ADR ETF,P,,Y,100.0,N,NaN,AADR,AADR,N

In [37]:
data_df.groupby("Listing Exchange")["Symbol"].nunique()

Listing Exchange
A     253
N    2520
P    1542
Q    3383
Z     351
Name: Symbol, dtype: int64

In [36]:
data_df.groupby("Listing Exchange")["Symbol"].count()

Listing Exchange
A     253
N    2520
P    1542
Q    3383
Z     351
Name: Symbol, dtype: int64

In [ ]:
unique_exchanges = data_df["Listing Exchange"].unique()

In [48]:
unique_exchanges.sort()

In [46]:
unique_exchanges

array(['A', 'N', 'P', 'Q', 'Z'], dtype=object)

In [49]:
data_df.head(5)

,Nasdaq Traded,Symbol,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
0,Y,A,"Agilent Technologies, Inc. Common Stock",N,,N,100.0,N,NaN,A,A,N
1,Y,AA,Alcoa Corporation Common Stock,N,,N,100.0,N,NaN,AA,AA,N
2,Y,AAAU,Perth Mint Physical Gold ETF,P,,Y,100.0,N,NaN,AAAU,AAAU,N
3,Y,AACG,ATA Creativity Global - American Depositary Sh...,Q,G,N,100.0,N,N,NaN,AACG,N
4,Y,AADR,AdvisorShares Dorsey Wright ADR ETF,P,,Y,100.0,N,NaN,AADR,AADR,N

In [53]:
data_df.groupby("Nasdaq Traded").count()

,Symbol,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
Nasdaq Traded,,,,,,,,,,,
Y,8049,8049,8049,8049,8049,8049,8049,3383,4666,8049,8049

In [54]:
data_df["Nasdaq Traded"].value_counts()

Nasdaq Traded
Y    8049
Name: count, dtype: int64

In [55]:
data_df["Nasdaq Traded"].unique()

array(['Y'], dtype=object)

In [57]:
	
data_df["Listing Exchange"].unique()

array(['N', 'P', 'Q', 'A', 'Z'], dtype=object)

In [58]:
data_df["Listing Exchange"].nunique()

5

In [65]:
data_df.info()
data_df.shape
data_df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8049 entries, 0 to 8048
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Nasdaq Traded     8049 non-null   object
 1   Symbol            8049 non-null   string
 2   Security Name     8049 non-null   object
 3   Listing Exchange  8049 non-null   object
 4   Market Category   8049 non-null   object
 5   ETF               8049 non-null   object
 6   Round Lot Size    8049 non-null   float64
 7   Test Issue        8049 non-null   object
 8   Financial Status  3383 non-null   object
 9   CQS Symbol        4666 non-null   object
 10  NASDAQ Symbol     8049 non-null   object
 11  NextShares        8049 non-null   object
dtypes: float64(1), object(10), string(1)
memory usage: 754.7+ KB

Nasdaq Traded               object
Symbol              string[python]
Security Name               object
Listing Exchange            object
Market Category             object
ETF                         object
Round Lot Size             float64
Test Issue                  object
Financial Status            object
CQS Symbol                  object
NASDAQ Symbol               object
NextShares                  object
dtype: object

In [66]:
data_df.dtypes

Nasdaq Traded               object
Symbol              string[python]
Security Name               object
Listing Exchange            object
Market Category             object
ETF                         object
Round Lot Size             float64
Test Issue                  object
Financial Status            object
CQS Symbol                  object
NASDAQ Symbol               object
NextShares                  object
dtype: object

In [67]:
data_df.describe()

       Round Lot Size
count     8049.000000
mean        99.942974
std          2.289194
min          1.000000
25%        100.000000
50%        100.000000
75%        100.000000
max        100.000000

In [69]:
data_df["Nasdaq Traded"] = data_df["Nasdaq Traded"].astype("category")

In [71]:
data_df.dtypes

Nasdaq Traded             category
Symbol              string[python]
Security Name               object
Listing Exchange            object
Market Category             object
ETF                         object
Round Lot Size             float64
Test Issue                  object
Financial Status            object
CQS Symbol                  object
NASDAQ Symbol               object
NextShares                  object
dtype: object

In [73]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8049 entries, 0 to 8048
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Nasdaq Traded     8049 non-null   category
 1   Symbol            8049 non-null   string
 2   Security Name     8049 non-null   object
 3   Listing Exchange  8049 non-null   object
 4   Market Category   8049 non-null   object
 5   ETF               8049 non-null   object
 6   Round Lot Size    8049 non-null   float64
 7   Test Issue        8049 non-null   object
 8   Financial Status  3383 non-null   object
 9   CQS Symbol        4666 non-null   object
 10  NASDAQ Symbol     8049 non-null   object
 11  NextShares        8049 non-null   object
dtypes: category(1), float64(1), object(9), string(1)
memory usage: 699.8+ KB

In [74]:
data_df.describe()

       Round Lot Size
count     8049.000000
mean        99.942974
std          2.289194
min          1.000000
25%        100.000000
50%        100.000000
75%        100.000000
max        100.000000

In [75]:
data_df.dtypes

Nasdaq Traded             category
Symbol              string[python]
Security Name               object
Listing Exchange            object
Market Category             object
ETF                         object
Round Lot Size             float64
Test Issue                  object
Financial Status            object
CQS Symbol                  object
NASDAQ Symbol               object
NextShares                  object
dtype: object

In [76]:
data_df.head()

,Nasdaq Traded,Symbol,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
0,Y,A,"Agilent Technologies, Inc. Common Stock",N,,N,100.0,N,NaN,A,A,N
1,Y,AA,Alcoa Corporation Common Stock,N,,N,100.0,N,NaN,AA,AA,N
2,Y,AAAU,Perth Mint Physical Gold ETF,P,,Y,100.0,N,NaN,AAAU,AAAU,N
3,Y,AACG,ATA Creativity Global - American Depositary Sh...,Q,G,N,100.0,N,N,NaN,AACG,N
4,Y,AADR,AdvisorShares Dorsey Wright ADR ETF,P,,Y,100.0,N,NaN,AADR,AADR,N

In [79]:
data_df["Listing Exchange"].unique()

array(['N', 'P', 'Q', 'A', 'Z'], dtype=object)

In [80]:
data_df["Listing Exchange"].nunique()

5

In [82]:
data_df.groupby("Listing Exchange").count()

,Nasdaq Traded,Symbol,Security Name,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
Listing Exchange,,,,,,,,,,,
A,253,253,253,253,253,253,253,0,253,253,253
N,2520,2520,2520,2520,2520,2520,2520,0,2520,2520,2520
P,1542,1542,1542,1542,1542,1542,1542,0,1542,1542,1542
Q,3383,3383,3383,3383,3383,3383,3383,3383,0,3383,3383
Z,351,351,351,351,351,351,351,0,351,351,351

In [87]:
data_df["Market Category"].unique()

array([' ', 'G', 'Q', 'S'], dtype=object)

In [88]:
data_df["Market Category"].nunique()

4

In [94]:
data_df.groupby("Market Category").count()

,Nasdaq Traded,Symbol,Security Name,Listing Exchange,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
Market Category,,,,,,,,,,,
,4666,4666,4666,4666,4666,4666,4666,0,4666,4666,4666
G,900,900,900,900,900,900,900,900,0,900,900
Q,1531,1531,1531,1531,1531,1531,1531,1531,0,1531,1531
S,952,952,952,952,952,952,952,952,0,952,952

In [98]:
data_df.head(5)

,Nasdaq Traded,Symbol,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
0,Y,A,"Agilent Technologies, Inc. Common Stock",N,,N,100.0,N,NaN,A,A,N
1,Y,AA,Alcoa Corporation Common Stock,N,,N,100.0,N,NaN,AA,AA,N
2,Y,AAAU,Perth Mint Physical Gold ETF,P,,Y,100.0,N,NaN,AAAU,AAAU,N
3,Y,AACG,ATA Creativity Global - American Depositary Sh...,Q,G,N,100.0,N,N,NaN,AACG,N
4,Y,AADR,AdvisorShares Dorsey Wright ADR ETF,P,,Y,100.0,N,NaN,AADR,AADR,N

In [107]:
len(data_df[data_df["Round Lot Size"]<100])

5

In [108]:
data_df[data_df["Round Lot Size"]<100]

,Nasdaq Traded,Symbol,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
743,Y,BH,Biglari Holdings Inc. Class B Common Stock,N,,N,10.0,N,NaN,BH,BH,N
1806,Y,DIT,AMCON Distributing Company Common Stock,A,,N,10.0,N,NaN,DIT,DIT,N
4662,Y,MKL,Markel Corporation Common Stock,N,,N,10.0,N,NaN,MKL,MKL,N
5169,Y,NVR,"NVR, Inc. Common Stock",N,,N,10.0,N,NaN,NVR,NVR,N
6406,Y,SEB,Seaboard Corporation Common Stock,A,,N,1.0,N,NaN,SEB,SEB,N

In [109]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8049 entries, 0 to 8048
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Nasdaq Traded     8049 non-null   category
 1   Symbol            8049 non-null   string
 2   Security Name     8049 non-null   object
 3   Listing Exchange  8049 non-null   object
 4   Market Category   8049 non-null   object
 5   ETF               8049 non-null   object
 6   Round Lot Size    8049 non-null   float64
 7   Test Issue        8049 non-null   object
 8   Financial Status  3383 non-null   object
 9   CQS Symbol        4666 non-null   object
 10  NASDAQ Symbol     8049 non-null   object
 11  NextShares        8049 non-null   object
dtypes: category(1), float64(1), object(9), string(1)
memory usage: 699.8+ KB